theme: jekyll-theme-minimal
title: [Open in DH]
logo:  https://raw.githubusercontent.com/rchampieux/openindh/master/_images/dh2018logo.png
description: [DH2018 | Mexico City | June 26-29 | #openindh]
